# Generated by Django 4.1.1 on 2022-09-25 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_name_alter_room_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.topiccolor'),
        ),
    ]
