# Generated by Django 4.1.1 on 2022-09-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_topiccolor_topic_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
